### ISSUE TITLE
Build Help

### ISSUE THREAD

**Issue by jwinters2119** [skrantzman/DNN_Tailwind#33]
Any updates to project coming? I can't seem to compile getting node sass error when trying to build... Seems like outdated files? Not experienced enough to say lol. Would love to get this up and running. Thanks!

**Comment by bbasarich** [comment]
I am also unable to get the project to install because of node-sass, with yarn output:
```
gyp info spawn args ]
Traceback (most recent call last):
  File "C:\inetpub\website\Portals\_default\Skins\DNN_Tailwind\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\inetpub\website\Portals\_default\Skins\DNN_Tailwind\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\inetpub\website\Portals\_default\Skins\DNN_Tailwind\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\inetpub\website\Portals\_default\Skins\DNN_Tailwind\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\inetpub\website\Portals\_default\Skins\DNN_Tailwind\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "C:\inetpub\website\Portals\_default\Skins\DNN_Tailwind\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2783, in Load
    variables, includes, depth, check, True)
  File "C:\inetpub\website\Portals\_default\Skins\DNN_Tailwind\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 399, in LoadTargetBuildFile
    includes, True, check)
  File "C:\inetpub\website\Portals\_default\Skins\DNN_Tailwind\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 271, in LoadOneBuildFile
    aux_data, includes, check)
  File "C:\inetpub\website\Portals\_default\Skins\DNN_Tailwind\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 308, in LoadBuildFileIncludesIntoDict
    LoadOneBuildFile(include, data, aux_data, None, False, check),
  File "C:\inetpub\website\Portals\_default\Skins\DNN_Tailwind\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 251, in LoadOneBuildFile
    None)
  File "C:\Users\username\.node-gyp\18.16.0\include\node\common.gypi", line 1
    'uv_library%': 'static_library',
                 ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\inetpub\website\Portals\_default\Skins\DNN_Tailwind\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\inetpub\\website\\Portals\\_default\\Skins\\DNN_Tailwind\\node_modules\\node-gyp\\bin\\node-gy
gs=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\inetpub\website\Portals\_default\Skins\DNN_Tailwind\node_modules\node-sass
gyp ERR! node -v v18.16.0

```
Has anyone been able to get this project to install recently?

**Comment by bbasarich** [comment]
OK, I think I finally got it to build.  Here are the steps I performed, starting with a clean DNN_Tailwind project folder:

1. Delete the package-lock.json file
2. In package.json file change gulp-sass version to "^5.1.0"
3. If you run gulp build, it will complain about two missing modules, so add them:
    a) npm install assert-plus
    b) npm install @fullhuman/postcss-purgecss
4. Run gulp build

It builds, and webpage using skin loads and looks to have TW CSS.  Time will tell if it's all working correctly.

**Comment by skrantzman** [comment]
My apologies, as the dependencies for this project are woefully outdated and DNN_Tailwind will not install or build with new versions of npm or yarn.  I do plan to update not only the dependencies, but also the version of TailwindCSS that is being used in the future.  In the meantime, to properly install and run DNN_Tailwind at this point, you should use node version manager (nvm) to install and use node v16.13.2 which uses npm v8.1.2 by default.  Using npm 8.1.2, DNN_Tailwind should install without errors.
